version: '3.8'

services:
  minerva_api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      # Persist both SQLite and ChromaDB data
      - minerva_data:/home/appuser/data
      - minerva_chroma:/home/appuser/chroma_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

volumes:
  minerva_data:
    driver: local
  minerva_chroma:
    driver: local 