[project]
name = "minerva"
version = "0.1.0"
description = "Document processing service for RAG applications"
requires-python = ">=3.11"
dependencies = [
    "openai",
    "boto3",
    "sqlalchemy",
    "psycopg2-binary",
    "python-dotenv",
    "pydantic",
    "pydantic-settings",
    "tiktoken"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
    "mypy",
    "pytest-cov"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"